version: '3.8'
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
